from hypothesis import given, strategies as st
from pydantic import ValidationError
from backend.app.schemas import MovieDetail


@given(
    id=st.integers(min_value=1),
    title=st.text(min_size=1),
    overview=st.text(),
    genres=st.lists(st.text(), min_size=0),
    vote_average=st.floats(min_value=0, max_value=10),
    release_date=st.dates().map(lambda d: d.isoformat()),
)
def test_movie_model_robustness(
    id, title, overview, genres, vote_average, release_date
):
    # This test ensures that the MovieDetail model can handle valid ranges of data
    # generated by Hypothesis without crashing.
    try:
        movie = MovieDetail(
            id=id,
            title=title,
            overview=overview,
            genres=genres,
            vote_average=vote_average,
            release_date=release_date,
            popularity=0.0,
            poster_path=None,
        )
        assert movie.id == id
        assert movie.title == title
    except ValidationError:
        # If ValidationError is raised, it might be due to constraints we set (e.g. strict types)
        # We just want to ensure it doesn't crash with unhandled exceptions.
        pass
